### ISSUE TITLE
Luminati proxy crashing when config file mounted from ConfigMap

### ISSUE THREAD

**Issue by igoratencompass** [luminati-io/luminati-proxy#122]
Hi,

We are experiencing the following crash in the Luminati proxy when running in Kubernetes:

```
2018-09-20 07:46:18.121 NOTICE: 22999 Stopping proxies 24000
2018-09-20 07:46:18.122 NOTICE: 22999 Stopping proxies 22225
2018-09-20 07:46:18.126 WARN: 22999 API error: POST /api/creds_user Error: EBUSY: resource busy or locked, rename '/root/.luminati.json' -> '/root/.luminati.json.backup'
    at Object.fs.renameSync (fs.js:784:18)
    at Manager.E.save_config (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/manager.js:714:12)
    at Etask.mgr_proxy_delete [as generator_ctor] (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/manager.js:1319:15)
    at mgr_proxy_delete.next (<anonymous>)
    at Etask.try_catch$loop (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:1452:54)
    at Etask.E._run (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:428:41)
    at Etask.E._got_retval (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:654:14)
    at /usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:351:23
    at Etask.E._complete (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:297:34)
    at Etask.E._next (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:331:10)
    at Etask.E._run (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:461:18)
    at Etask.E._got_retval (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:654:14)
    at /usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:351:23
    at Etask.E._complete (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:297:34)
    at Etask.E._next (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:331:10)
    at Etask.E._run (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/hutil/util/etask.js:461:18)
```

I have tested multiple versions of the proxy from your Github repository and they all exhibit the same issue. They all run fine until we try to login to the UI on port 22999 when the above error happens and Luminti crashes. In the most recent versions it is even worse with the error happening on startup so the proxy never even gets to run.

Now let me explain little bit around `/root/.luminati.json` file. This is a ConfigMap that we mount as `/root/.luminati.json` file inside the Luminati proxy pod. This might be the reason that renaming this file is not going to work in our case (see the error above).

Can you please advise if there is any workaround for this issue? Maybe copy operation instead or rename would be more appropriate in this case for the /api/creds_user API call to take backup of the file.

Thanks.

**Comment by igoratencompass** [comment]
Workaround is to mount the ConfigMap to an intermittent location and then copy to the config location via lifecycle hook:

```
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp /tmp/.luminati.json /root/.luminati.json"]
        volumeMounts:
        - mountPath: "/tmp/.luminati.json"
          name: config-volume
          subPath: ".luminati.json"
      volumes:
        - name: config-volume
          configMap:
            name: luminati-config
            items:
            - key: luminati.json
              path: ".luminati.json"
```
