### ISSUE TITLE
Load configuration through Docker Swarm or Compose

### ISSUE THREAD

**Issue by estebanbouza** [luminati-io/luminati-proxy#146]
Currently, the documentation states that pre-configured settings can be used in docker by creating a volume, modifying it, and using it with `docker` command.

```
1. docker volume create lpm-vol
2. cd /var/lib/docker/volumes/lpmvol/_data
3. put .luminati.json to this directory (here also will be the logs and other files generated by the container)
4. docker run --rm --name 'lpm1' --mount source=lpmvol,target=/root
"luminati/luminati-proxy" luminati
```

However this approach is not suitable when using luminati as part of docker compose or docker swarm. If a directory with a single `.luminati.json` file is mapped as a docker volume, the config file is ignored or overwritten after booting.

For example:
```
cp /home/ubuntu/lpm/.luminati.json /luminati/
```

In `docker-compose.yml`:
```
luminati:
    image: luminati/luminati-proxy
    command: luminati --www_whitelist_ips 0.0.0.0/0 --whitelist_ips 0.0.0.0/0
    volumes:
      - "/luminati:/root"
```

After running the compose commands, the configuration disappears after some time and/or is not applied in the LPM
```
ls -lha /luminati
total 20K
drwxrwxrwx  5 root root 4.0K Nov 11 12:19 .
drwxr-xr-x 24 root root 4.0K Nov 11 12:17 ..
drwx------  3 root root 4.0K Nov 11 12:19 .config
drwxr-xr-x  5 root root 4.0K Nov 11 12:18 .pm2
drwxr-xr-x  2 root root 4.0K Nov 11 12:19 luminati_proxy_manager
```

Expectation:
The volume that I'm mapping to the container should be empty, and read the configuration file that I'm dropping so that configuration isn't lost between reboots.

**Comment by fudali** [comment]
Hi, it seems to be strictly docker related question, not related to LPM

**Comment by estebanbouza** [comment]
This cannot be fixed through docker only. The way config files are structured with LPM makes it very hard, if not impossible to use LPM with dynamic config and docker. 

Can this be reopened ?

**Comment by fudali** [comment]
Can you suggest any change in LPM behavior that would solve your issue?

**Comment by ramanqul** [comment]
As an alternative solution I can suggest to create your own Dockerfile, for instance:

```
FROM luminati/luminati-proxy
RUN apt-get update
RUN apt-get install net-tools
COPY myluminati.json /root/.luminati.json

```
And after that in your docker-compose file point to that build image:
```

version: '3.7'

services:
  proxy:
    build: .
    image: com.xyz/do_luminati_proxy:latest
    container_name: do_luminati_proxy
    ports:
      - "22225:22225"
      - "24000:24000"
    restart: always
    command: luminati --no-www
```

As you can see I don't use any volumes. It works for me.
