### ISSUE TITLE
Adding custom config file when docker and volume is not working

### ISSUE THREAD

**Issue by mdemou** [luminati-io/luminati-proxy#151]
When I try to run luminati docker image with a custom config json, it returns **Error: EBUSY: resource busy or locked, rename '/root/luminati.json' -> '/root/luminati.json.backup'**

```
luminati    | Loaded config /root/luminati.json
luminati    | Running proxy configurations...
luminati    | 2018-11-30 12:15:34.808 ERR: 22999 start error Error: EBUSY: resource busy or locked, rename '/root/luminati.json' -> '/root/luminati.json.backup'
luminati    |     at Object.renameSync (fs.js:591:3)
luminati    |     at Manager.E.save_config (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/manager.js:676:12)
luminati    |     at Manager.E.config_check (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/manager.js:1775:10)
luminati    |     at Etask.mgr_start [as generator_ctor] (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/manager.js:2955:15)
luminati    |     at mgr_start.next (<anonymous>)
luminati    |     at Etask.try_catch$loop (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:1460:54)
luminati    |     at Etask.E._run (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:436:41)
luminati    |     at Etask.E._got_retval (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:662:14)
luminati    |     at /usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:359:23
luminati    |     at Etask.E._complete (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:305:34)
```

this is my custom config file
```
{
  "_defaults": {
    "customer": "xxxx",
    "password": "xxxx",
    "whitelist_ips": [
      "172.17.0.1"
    ]
  },
  "proxies": [
    {
      "keep_alive": 45,
      "last_preset_applied": "round_robin",
      "max_requests": 1,
      "pool_type": "round-robin",
      "port": 24000,
      "random_user_agent": true,
      "session": true,
      "ssl": true
    }
  ]
}
```

this is my docker-compose file
```
  luminati:
    image: luminati/luminati-proxy:latest
    container_name: luminati
    ports:
      - "22999:22999"
      - "24000:24000"
    restart: always
    environment:
      LPM_CUSTOMER: xxxx
      LPM_ZONE: xxxx
      LPM_PASSWORD: xxxx
      LPM_PROXY: xxxx
      LPM_PROXY_PORT: 22225
      LPM_WWW_WHITELIST_IPS: "172.17.0.1"
      LPM_SSL: "true"
      LPM_CONFIG: "/root/luminati.json"
    volumes:
      - ./volumes/luminati.json:/root/luminati.json
    command: ["luminati"]
```

I don't know if it is something about permissions or what is going on. I tried a lot of ways, and it does not work.

**Comment by admerzeau** [comment]
@mdemou this is how I do it:

```
proxy:
    image: luminati/luminati-proxy:latest
    ports:
      - "22999:22999"
    restart: always
    environment:
      LPM_CUSTOMER: xxxxxx
      LPM_ZONE: xxxxx
      LPM_PASSWORD: xxxxxxx
      LPM_PROXY_PORT: 22225
      LPM_WWW_WHITELIST_IPS: "0.0.0.0/0"
      LPM_SSL: "true"
      LPM_CONFIG: "/etc/luminati/luminati.json"
      LPM_DATABASE: "/root/luminati-logs.sqlite3"
    command: ["luminati"]
    volumes:
      - ./tools/docker/provision/luminati:/etc/luminati/
      - ./luminati-volume:/root/

```
Right now I mounting two volumes one with the configuration and the other to get the database logs even is the container is restarted, I am pretty sure you can do it using only one volume but for me that the way I need to do it. Let me know how goes for you.
